class MyConstants {
  apiEndpoints = Object.freeze({
    addActivity: "/api/add-activity",
    authenticate: "/api/authenticate",
  });
  headers = Object.freeze({
    activities: {
      date: "Date",
      activity: "Activity",
    },
    affiliates: {
      name: "Name",
      phoneNumber: "Phone",
      email: "Email",
      totalFees: "Total Fees",
      paidFees: "Paid Fees",
      pendingFees: "Pending Fees",
      joined: "Joined",
    },
    cashFlow: {
      id: "ID",
      date: "Date",
      client: "Client",
      company: "Company",
      project: "Project",
      particulars: "Particulars",
      paymentFor: "Payment For",
      amountReceived: "Amt Received",
      professionalFees: "PF",
      reimbursementVoucher: "RV",
      amountPaid: "Amt Paid",
      totalBalance: "Total Balance",
      isOfficeExpense: "Is Office Exp",
    },
    clients: {
      id: "ID",
      name: "Name",
      phone: "Phone",
      email: "Email",
      joined: "Joined",
    },
    inquiry: {
      date: "Date",
      client: "Client",
      phone: "Phone",
      mainProject: "Main Project",
      subProject: "Sub Project",
      reference: "Reference",
      followUps: "Follow Ups",
      quote: "Quote",
      status: "Status",
      notes: "Notes",
      creator: "Creator",
    },
    invoices: {
      id: "ID",
      client: "Client",
      project: "Project",
      generated: "Generated",
      amount: "Amount",
      amountReceived: "Amt Received",
      rvId: "RV ID",
      rvTotal: "RV Total",
      status: "Status",
      file: "File",
    },
    notes: {
      date: "Date",
      note: "Note",
      writer: "Writer",
    },
  });
  messages: { [key: string]: string } = Object.freeze({
    accessRevoked: "Your access has been revoked.",
    addEmployee: "New employee added.",
    adminCompanyAdded: "New admin company added.",
    adminCompanyEdit: "Admin company edited.",
    affiliateAdded: "Affiliate(s) added.",
    apiCallForbidden: "Invalid API method.",
    badRequest: "Incompatible request sent.",
    cashFlowEntryAdded: "Cash Flow added.",
    companyAdded: "New company added.",
    companyEdited: "Company edited.",
    employeeEdited: "Employee edited.",
    filesDeleted: "File(s) deleted.",
    governmentIdAdded: "Government ID added.",
    inquiryAdded: "New inquiry added.",
    inquiryClosed: "Inquiry closed.",
    inquiryConvertedToProject: "Inquiry converted to Project.",
    inquiryUpdated: "Inquiry updated.",
    invoiceAdded: "New invoice added.",
    invoiceEdited: "Invoice edited.",
    noDataFound: "No data found.",
    noteAdded: "New note added.",
    noteUpdated: "Note updated.",
    profileEdited: "Profile edited.",
    projectEdited: "Project edited.",
    projectDeleted: "Project deleted.",
    quoteEdited: "Quote edited.",
    settingsUpdated: "Settings updated.",
    someErrorOccurred: "Something went wrong. Contact help desk.",
    statusChanged: "Status updated.",
    taskAdded: "New task added.",
    taskDisabled: "Task disabled.",
    taskEnabled: "Task enabled.",
    taskUpdated: "Task updated.",
    unauthorizedAccess: "Unauthorized access.",
  });
}

export default new MyConstants();
