"use client";

const MyConstants = Object.freeze({
	API_ENDPOINTS: Object.freeze({
		addActivity: "/api/add-activity",
		authenticate: "/api/authenticate",
		getPermissions: "/api/get-permissions",
	}),
	MESSAGES: Object.freeze({
		accessRevoked: "Your access has been revoked.",
		addEmployee: "New employee added.",
		adminCompanyAdded: "New admin company added.",
		adminCompanyEdit: "Admin company edited.",
		affiliateAdded: "Affiliate(s) added.",
		apiCallForbidden: "Invalid API method.",
		badRequest: "Incompatible request sent.",
		cashFlowEntryAdded: "Cash Flow added.",
		companyAdded: "New company added.",
		companyEdited: "Company edited.",
		employeeEdited: "Employee edited.",
		filesDeleted: "File(s) deleted.",
		governmentIdAdded: "Government ID added.",
		inquiryAdded: "New inquiry added.",
		inquiryClosed: "Inquiry closed.",
		inquiryConvertedToProject: "Inquiry converted to Project.",
		inquiryUpdated: "Inquiry updated.",
		invoiceAdded: "New invoice added.",
		invoiceEdited: "Invoice edited.",
		noAtSymbolInEmailAddress: "<span>Must contain <b>@</b> symbol.</span>",
		noDataFound: "No data found.",
		noEmailAddress: "Type your Spire account's email address.",
		noPassword: "Type your Spire account's password.",
		noPeriodSymbolInEmailAddress: "<span>Must contain <b>.</b> symbol.</span>",
		noteAdded: "New note added.",
		noteUpdated: "Note updated.",
		profileEdited: "Profile edited.",
		projectEdited: "Project edited.",
		projectDeleted: "Project deleted.",
		quoteEdited: "Quote edited.",
		settingsUpdated: "Settings updated.",
		someErrorOccurred: "Something went wrong. Contact help desk.",
		spireDomainOnly: "<span>Domain must exactly be <b>spire.com</b>.</span>",
		statusChanged: "Status updated.",
		taskAdded: "New task added.",
		taskDisabled: "Task disabled.",
		taskEnabled: "Task enabled.",
		taskUpdated: "Task updated.",
		unauthorizedAccess: "Unauthorized access.",
	}),
	NOTIFICATION_TYPES: Object.freeze({
		error: "error",
		info: "info",
		success: "success",
		warning: "warning",
	}),
});

export default MyConstants;
