"use client";

const MyConstants = Object.freeze({
	API_ENDPOINTS: Object.freeze({
		addActivity: "/api/add-activity",
		authenticate: "/api/authenticate",
		getPermissions: "/api/get-permissions",
	}),
	TABLE_HEADERS: Object.freeze({
		activities: Object.freeze({
			date: "Date",
			activity: "Activity",
		}),
		affiliates: Object.freeze({
			name: "Name",
			phone: "Phone",
			email: "Email",
			totalFees: "Total Fees",
			paidFees: "Paid Fees",
			pendingFees: "Pending Fees",
			joined: "Joined",
		}),
		cashFlow: Object.freeze({
			id: "ID",
			date: "Date",
			client: "Client",
			company: "Company",
			project: "Project",
			particulars: "Particulars",
			paymentFor: "Payment For",
			amountReceived: "Amt Received",
			professionalFees: "PF",
			reimbursementVoucher: "RV",
			amountPaid: "Amt Paid",
			totalBalance: "Total Balance",
			isOfficeExpense: "Is Office Exp",
		}),
		clients: Object.freeze({
			id: "ID",
			name: "Name",
			phone: "Phone",
			email: "Email",
			joined: "Joined",
		}),
		inquiries: [
			{ field: "entry_date", headerName: "Entry Date", width: 200 },
			{ field: "client_id", headerName: "Client", width: 120 },
			{ field: "contact_number", headerName: "Contact Number", width: 150 },
			{ field: "main_project_id", headerName: "Main Project", width: 150 },
			{ field: "sub_project_id", headerName: "Sub Project", width: 150 },
			{ field: "reference_id", headerName: "Reference", width: 120 },
			{ field: "follow_ups", headerName: "Follow Ups", width: 150 },
			{ field: "quote", headerName: "Quote", width: 120 },
			{ field: "status", headerName: "Status", width: 120 },
			{ field: "", headerName: "Notes", width: 120 },
			{ field: "created_by", headerName: "Created By", width: 150 },
			{ field: "inquiry_type_id", headerName: "Inquiry Type", width: 150 },
		],
		inquiry: Object.freeze({
			date: "Date",
			client: "Client",
			phone: "Phone",
			mainProject: "Main Project",
			subProject: "Sub Project",
			reference: "Reference",
			followUps: "Follow Ups",
			quote: "Quote",
			tags: "Tags",
			status: "Status",
			notes: "Notes",
			creator: "Creator",
		}),
		invoices: Object.freeze({
			id: "ID",
			client: "Client",
			project: "Project",
			generated: "Generated",
			amount: "Amount",
			amountReceived: "Amt Received",
			rvId: "RV ID",
			rvTotal: "RV Total",
			status: "Status",
			file: "File",
		}),
		notes: Object.freeze({
			date: "Date",
			note: "Note",
			writer: "Writer",
		}),
		paymentReceived: Object.freeze({
			date: "Date",
			mode: "Mode",
			amount: "Amount",
		}),
		projectNotes: Object.freeze({
			date: "Date",
			note: "Note",
			writer: "Writer",
		}),
		projects: Object.freeze({
			id: "ID",
			governmentId: "Gov ID",
			client: "Client",
			company: "Company",
			mainProject: "Main Project",
			subProject: "Sub Project",
			// affiliates: "Affiliates",
			teams: "Teams",
			dueOn: "Due On",
			lastNote: "Last Note",
			status: "Status",
		}),
		remuneration: Object.freeze({
			date: "Date",
			client: "Client",
			company: "Company",
			project: "Project",
			particulars: "Particulars",
			amountReceived: "Amt Received",
			ag: "AG",
			ds: "DS",
			provision: "Provision",
		}),
		singleAffiliate: Object.freeze({
			mappedToClient: "Mapped To Client",
			mappedToProject: "Mapped To Project",
			adjustedTowardsProject: "Adjusted Towards Project",
			adjustedFees: "Adjusted Fees",
			paidFees: "Paid Fees",
			pendingFees: "Pending Fees",
			totalFees: "Total Fees",
		}),
		singleClientProjects: Object.freeze({
			id: "ID",
			startedOn: "Started",
			project: "Project",
			company: "Company",
			allottedTo: "Alloted To",
			affiliates: "Affiliates",
			invoiceFirm: "Invoice Firm",
			professionalFees: "Prof Fees",
			affiliatesFees: "Aff Fees",
			reimbursementVoucher: "RV",
			amountReceived: "Received",
			amountPending: "Pending",
			total: "Total",
			dueOn: "Due",
			status: "Status",
		}),
		singleProject: Object.freeze({
			id: "ID",
			task: "Task",
			dueOn: "Due On",
			addedBy: "Added By",
			remarks: "Remarks",
			expense: "Expense",
			action: "Actions",
		}),
	}),
	MESSAGES: Object.freeze({
		accessRevoked: "Your access has been revoked.",
		addEmployee: "New employee added.",
		adminCompanyAdded: "New admin company added.",
		adminCompanyEdit: "Admin company edited.",
		affiliateAdded: "Affiliate(s) added.",
		apiCallForbidden: "Invalid API method.",
		badRequest: "Incompatible request sent.",
		cashFlowEntryAdded: "Cash Flow added.",
		companyAdded: "New company added.",
		companyEdited: "Company edited.",
		employeeEdited: "Employee edited.",
		filesDeleted: "File(s) deleted.",
		governmentIdAdded: "Government ID added.",
		inquiryAdded: "New inquiry added.",
		inquiryClosed: "Inquiry closed.",
		inquiryConvertedToProject: "Inquiry converted to Project.",
		inquiryUpdated: "Inquiry updated.",
		invoiceAdded: "New invoice added.",
		invoiceEdited: "Invoice edited.",
		noAtSymbolInEmailAddress: "<span>Must contain <b>@</b> symbol.</span>",
		noDataFound: "No data found.",
		noEmailAddress: "Type your Spire account's email address.",
		noPassword: "Type your Spire account's password.",
		noPeriodSymbolInEmailAddress: "<span>Must contain <b>.</b> symbol.</span>",
		noteAdded: "New note added.",
		noteUpdated: "Note updated.",
		profileEdited: "Profile edited.",
		projectEdited: "Project edited.",
		projectDeleted: "Project deleted.",
		quoteEdited: "Quote edited.",
		settingsUpdated: "Settings updated.",
		someErrorOccurred: "Something went wrong. Contact help desk.",
		spireDomainOnly: "<span>Domain must exactly be <b>spire.com</b>.</span>",
		statusChanged: "Status updated.",
		taskAdded: "New task added.",
		taskDisabled: "Task disabled.",
		taskEnabled: "Task enabled.",
		taskUpdated: "Task updated.",
		unauthorizedAccess: "Unauthorized access.",
	}),
	NOTIFICATION_TYPES: Object.freeze({
		error: "error",
		info: "info",
		success: "success",
		warning: "warning",
	}),
	PAGE_ROUTES: Object.freeze({
		admins: "/home/admins",
		affiliates: "/home/affiliates",
		cashFlow: "/home/cash-flow",
		clients: "/home/clients",
		companies: "/home/companies",
		dashboard: "/home/dashboard",
		employees: "/home/employees",
		inquiries: "/home/inquiries",
		invoices: "/home/invoices",
		projects: "/home/projects",
		tasks: "/home/tasks",
	}),
});

export default MyConstants;
