"use client";

const MyConstants = Object.freeze({
	ApiEndpoints: Object.freeze({
		Activities: "/api/activities",
		Affiliates: Object.freeze({
			AddAffiliate: "api/affiliates/addAffiliates",
			AddTransaction: "api/affiliates/addTransaction",
			EditTransaction: "api/affiliates/editTransaction",
			GetAffiliates: "api/affiliates/getAffiliates",
			GetMappedAffiliates: "api/affiliates/getMappedAffiliates",
			GetNewTransactionSupportData: "api/affiliates/getNewTransactionSupportData",
			GetTransactionsSupportData: "api/affiliates/getTransactionsSupportData",
			UnmapAffiliate: "api/affiliates/unmapAffiliate",
		}),
		Authenticate: "/api/authenticate",
		CashFlows: Object.freeze({
			Modules: Object.freeze({
				Entities: Object.freeze({
					AddEntity: "api/cashFlows/modules/entities/addEntity",
					AddHead: "api/cashFlows/modules/entities/addHead",
					GetEntities: "api/cashFlows/modules/entities/getEntities",
					GetHeads: "api/cashFlows/modules/entities/getHeads",
					GetNewHeadSupportData: "api/cashFlows/modules/entities/getNewHeadSupportData",
				}),
				AddTransaction: "api/cashFlows/modules/addTransaction",
				EditTransaction: "api/cashFlows/modules/editTransaction",
				GetNewTransactionSupportData: "api/cashFlows/modules/getNewTransactionSupportData",
				PettyCash: Object.freeze({
					AddTransaction: "api/cashFlows/modules/pettyCash/addTransaction",
					EditTransaction: "api/cashFlows/modules/pettyCash/editTransaction",
					GetTransactions: "api/cashFlows/modules/pettyCash/getTransactions",
				}),
				GetTransactions: "api/cashFlows/modules/getTransactions",
			}),
			GetAllTransactions: "api/cashFlows/getAllTransactions",
			GetSupportData: "api/cashFlows/getSupportData",
		}),
		Clients: Object.freeze({
			DeleteFile: "api/clients/deleteFile",
			GetClients: "api/clients/getClients",
			GetFiles: "api/clients/getFiles",
			GetSupportData: "api/clients/getSupportData",
			UploadFiles: "api/clients/uploadFiles",
		}),
		Dashboard: "api/dashboard/getSupportData",
		GetMySpace: "api/dashboard/getMySpaceData",
		Employees: Object.freeze({
			AddEmployee: "api/employees/addEmployee",
			EditEmployee: "api/employees/editEmployee",
			GetSupportData: "api/employees/getSupportData",
		}),
		ErrorLogger: "api/errorLogger",
		Firms: Object.freeze({
			AddFirm: "api/firms/addFirm",
			EditBank: "api/firms/editBank",
			EditFirm: "api/firms/editFirm",
			GetFirms: "api/firms/getFirms",
		}),
		Getter: "api/getter",
		Inquiries: Object.freeze({
			AddInquiry: "api/inquiries/addInquiry",
			AddQuotation: "api/inquiries/addQuotation",
			EditInquiry: "api/inquiries/editInquiry",
			GetInquiries: "api/inquiries/getInquiries",
			GetMyInquiries: "api/inquiries/getMyInquiries",
			GetAddQuotationSupport: "api/inquiries/getAddQuotationSupport",
			GetSupportData: "api/inquiries/getSupportData",
			UploadQuotation: "api/inquiries/uploadQuotation",
		}),
		Invoices: Object.freeze({
			AddInvoice: "api/invoices/addInvoice",
			AddTransaction: "api/invoices/addTransaction",
			EditInvoice: "api/invoices/editInvoice",
			GetHistorySupportData: "api/invoices/getHistorySupportData",
			GetNewInvoiceSupportData: "api/invoices/getNewInvoiceSupportData",
			GetSupportData: "api/invoices/getSupportData",
			UploadInvoice: "api/invoices/uploadInvoice",
		}),
		Notes: Object.freeze({
			AddNote: "api/notes/addNote",
			GetNotes: "api/notes/getNotes",
		}),
		Projects: Object.freeze({
			AddProject: "api/projects/addProject",
			EditProject: "api/projects/editProject",
			GetMyProjects: "api/projects/getMyProjects",
			GetProjects: "api/projects/getProjects",
			GetStatus: "api/projects/getStatus",
			GetSupportData: "api/projects/getSupportData",
		}),
		Rv: Object.freeze({
			AddRv: "api/rv/addRv",
			AddTransaction: "api/rv/addTransaction",
			EditRv: "api/rv/editRv",
			GetNewRvSupportData: "api/rv/getNewRvSupportData",
			GetNewTransactionSupportData: "api/rv/getNewTransactionSupportData",
			GetSupportData: "api/rv/getSupportData",
			UploadRv: "api/rv/uploadRv",
		}),
		Setter: "api/setter",
		SingleProject: Object.freeze({
			GetSupportData: "api/singleProject/getSupportData",
			MapAffiliate: "api/singleProject/mapAffiliates",
		}),
		Tasks: Object.freeze({
			AddTask: "api/tasks/addTask",
			SortTasks: "api/tasks/sortTasks",
		}),
		Vendors: Object.freeze({
			AddHead: "api/vendors/addHead",
			AddVendor: "api/vendors/addVendors",
			AddTransaction: "api/vendors/addTransaction",
			EditTransaction: "api/vendors/editTransaction",
			GetHeads: "api/vendors/getHeads",
			GetNewTransactionSupportData: "api/vendors/getNewTransactionSupportData",
			GetTransactionsSupportData: "api/vendors/getTransactionsSupportData",
			GetVendors: "api/vendors/getVendors",
		}),
	}),
	EmploymentType: Object.freeze({
		AnnuallyConfirmed: "Annually Confirmed",
		Articleship: "Articleship",
		HalfYearlyConfirmed: "Half Yearly Confirmed",
		Intern: "Intern",
		OnContract: "On Contract",
		Permanent: "Permanent",
		QuarterlyConfirmed: "Quarterly Confirmed",
	}),
	Designation: Object.freeze({
		BusinessAssociate: "Business Associate",
		ComplianceAssociate: "Compliance Associate",
		HrOfficer: "HR Officer",
		OfficeBoy: "Office Boy",
	}),
	Gender: Object.freeze({
		Male: "Male",
		Female: "Female",
		Other: "Other",
		PreferNotToSay: "Prefer Not To Say",
	}),
	IpAddresses: Object.freeze({
		Office: "192.168.20.101",
		Remote: "192.168.20.102",
	}),
	Messages: Object.freeze({
		AccessRevoked: "Your access has been revoked.",
		AffiliateAdded: "Affiliate(s) added.",
		AffiliateUnmapped: "Affiliate unmapped.",
		AllSubTasksMarkedCompleted: "All sub tasks marked completed.",
		ApiCallForbidden: "Invalid API method.",
		BadRequest: "Incompatible request sent.",
		BankEdited: "Bank edited.",
		CardAdded: "Card added.",
		CashFlowAdded: "Cash Flow added.",
		CashFlowEdited: "Cash Flow edited.",
		ClientEdited: "Client edited.",
		CompanyAdded: "New company added.",
		CompanyEdited: "Company edited.",
		EmployeeAdded: "New employee added.",
		EmployeeEdited: "Employee edited.",
		EntityAdded: "Entity added.",
		FilesDeleted: "File(s) deleted.",
		GovernmentIdAdded: "Government ID added.",
		GovernmentIdEdited: "Government ID edited.",
		InquiryAdded: "New inquiry added.",
		InquiryClosed: "Inquiry closed.",
		InquiryConvertedToProject: "Inquiry converted to Project.",
		InquiryEdited: "Inquiry edited.",
		InvalidUser: "Invalid user.",
		InvoiceAdded: "New invoice added.",
		InvoiceEdited: "Invoice edited.",
		NoAtSymbolInEmailAddress: "Must contain @ symbol.",
		NoDataFound: "No data found.",
		NoEmailAddress: "Type your email address.",
		NoPassword: "Type your password.",
		NoPeriodSymbolInEmailAddress: "Must contain period (.) symbol.",
		NoteAdded: "New note added.",
		NoteEdited: "Note edited.",
		FirmAdded: "New firm added.",
		FirmEdited: "Firm edited.",
		ProfileEdited: "Profile edited.",
		ProjectClosed: "Project closed.",
		ProjectCompleted: "Project completed.",
		ProjectDeleted: "Project deleted.",
		ProjectEdited: "Project edited.",
		ProjectStatusEdited: "Project status edited.",
		QuotationAdded: "Quotation added.",
		QuoteEdited: "Quote edited.",
		RvAdded: "New reimbursement voucher added.",
		RvEdited: "Reimbursement voucher edited.",
		SettingsEdited: "Settings edited.",
		SomeErrorOccurred: "Something went wrong. Contact help desk.",
		SpireDomainOnly: "Domain must exactly be spire.com.",
		StartingBalanceAdded: "Starting balance added.",
		StatusEdited: "Status edited.",
		SubTaskMarkedCompleted: "Sub task marked completed.",
		TaskAdded: "New task added.",
		TaskDeleted: "Task deleted",
		TaskDisabled: "Task disabled.",
		TaskEdited: "Task edited.",
		TaskEnabled: "Task enabled.",
		TaskParticularRemarkAdded: "Task Particular/Remark added.",
		TaskParticularRemarkDeleted: "Task Particular/Remark deleted.",
		TaskParticularRemarkEdited: "Task Particular/Remark edited.",
		TransactionAdded: "Transaction added.",
		TransactionEdited: "Transaction edited.",
		UnauthorizedAccess: "Unauthorized access.",
		VendorAdded: "Vendor(s) added.",
	}),
	Modules: Object.freeze({
		Base: Object.freeze({
			Affiliates: "Affiliates",
			CashFlow: "Cash Flow",
			Clients: "Clients",
			Companies: "Companies",
			Dashboard: "Dashboard",
			Employees: "Employees",
			Inquiries: "Inquiries",
			Invoices: "Invoices",
			MySpace: "My Space",
			Notes: "Notes",
			Firms: "Firms",
			Projects: "Projects",
			References: "References",
			Rv: "RV",
			Tasks: "Tasks",
			Vendors: "Vendors",
		}),
		Derived: Object.freeze({
			DeleteAffiliate: "Delete Affiliate",
			DeleteCashFlow: "Delete Cash Flow",
			DeleteClient: "Delete Client",
			DeleteCompany: "Delete Company",
			DeleteEmployee: "Delete Employee",
			DeleteInquiry: "Delete Inquiry",
			DeleteInvoice: "Delete Invoice",
			DeleteSubTask: "Delete Sub Task",
			DeleteProject: "Delete Project",
			DeleteReference: "Delete Reference",
			DeleteRv: "Delete RV",
			DeleteTask: "Delete Task",
			DeleteTaskFromReimburseVoucher: "Delete Task From Reimburse Voucher",
			DisableTask: "Disable Task",
			EditAffiliate: "Edit Affiliate",
			EditCashFlow: "Edit Cash Flow",
			EditClient: "Edit Client",
			EditCompany: "Edit Company",
			EditEmployee: "Edit Employee",
			EditInquiry: "Edit Inquiry",
			EditInvoice: "Edit Invoice",
			EditFirm: "Edit Firm",
			EditProject: "Edit Project",
			EditReference: "Edit Reference",
			EditRv: "Edit RV",
			EditSubTask: "Edit Sub Task",
			EditTask: "Edit Task",
			EnableTask: "Enable Task",
			MarkSubTaskCompleted: "Mark Sub Task Completed",
			MarkTaskCompleted: "Mark Task Completed",
			NewAffiliate: "New Affiliate",
			NewInquiry: "New Inquiry",
			NewInvoice: "New Invoice",
			NewFirm: "New Firm",
			NewProject: "New Project",
			NewRv: "New RV",
			NewQuotation: "New Quotation",
			NewTask: "New Task",
			NewVendor: "New Vendor",
			PaymentReceived: "Payment Received",
		}),
		Other: Object.freeze({
			CashFlow: Object.freeze({
				All: "All",
				Inward: "Inward",
				Outward: "Outward",
			}),
			CashFlowModules: Object.freeze({
				OfficeExpense: { id: "OFEX", name: "Office Expense" },
				OtherExpense: { id: "OTEX", name: "Other Expense" },
				OtherIncome: { id: "OTIN", name: "Other Income" },
				PettyCash: { id: "PECA", name: "Petty Cash" },
			}),
			Employees: Object.freeze({
				Edit: "Edit",
				New: "New",
			}),
			Files: Object.freeze({
				Existing: "Existing",
				New: "New",
			}),
			Firms: Object.freeze({
				EditBanks: "Edit Bank",
				EditFirm: "Edit Firm",
			}),
			SingleClient: "Single Client",
			SingleProject: "Single Project",
		}),
	}),
	Statuses: Object.freeze({
		Inquiries: Object.freeze({
			Closed: "Closed",
			Confirmed: "Confirmed",
			Hold: "Hold",
			Open: "Open",
		}),
		Projects: Object.freeze({
			Active: "Active",
			Cancelled: "Cancelled",
			Closed: "Closed",
			Completed: "Completed",
			Hold: "Hold",
		}),
		Tasks: Object.freeze({
			Completed: "Completed",
			Disable: "Disable",
			Enable: "Enable",
		}),
	}),
	TableHeaders: Object.freeze({
		Activities: Object.freeze({
			EntryAt: "Entry At",
			Module: "Module",
			Activity: "Activity",
			EntryBy: "Entry By",
		}),
		Clients: Object.freeze({
			Id: "ID",
			Name: "Name",
			PhoneNumber: "Phone Number",
			EmailAddress: "Email Address",
			JoinedOn: "Joined On",
		}),
		Inquiries: Object.freeze({
			Client: "Client",
			Contacts: "Contacts",
			Projects: "Projects",
			FollowUps: "Follow Ups",
			Quote: "Quote",
			NextFollowUpOn: "Next Follow Up",
			Status: "Status",
			References: "References",
		}),
		MyInquiries: Object.freeze({
			EntryDate: "Date",
			Client: "Client & Inquiry DT",
			PhoneNumber: "Contact Info",
			MainProject: "Projects",
			SubProject: "Sub Project",
			Reference: "Reference",
			FollowUps: "Follow Ups",
			Quote: "Quote",
			Status: "Status",
			Notes: "Notes",
			CreatedBy: "Created By",
		}),
		Invoices: Object.freeze({
			Id: "ID",
			Company: "Company",
			MainProject: "Main Project",
			SubProject: "Sub Project",
			CreatedAt: "Created At",
			DueDate: "Due Date",
			Amount: "Amount",
			AmountReceived: "Received",
			AmountPending: "Pending",
			InvoiceId: "Invoice ID",
			Actions: "Actions",
		}),
		MappedAffiliates: Object.freeze({
			Name: "Name",
			Paid: "Paid",
			Fees: "Fees",
			Action: "Action",
		}),
		Notes: Object.freeze({
			date: "Date",
			note: "Note",
			entryBy: "Entry By",
		}),
		Projects: Object.freeze({
			Started: "Started On",
			GovermentId: "Gov ID",
			Client: "Client",
			Company: "Company",
			MainProject: "Main Project",
			SubProject: "Sub Project",
			Teams: "Teams",
			Status: "Status",
		}),
		ReimburseVouchers: Object.freeze({
			Id: "ID",
			Company: "Company",
			MainProject: "Main Project",
			SubProject: "Sub Project",
			CreatedAt: "Created At",
			Amount: "Amount",
			AmountReceived: "Received",
			AmountPending: "Pending",
			RvId: "RV ID",
			Actions: "Actions",
		}),
		SingleClient: Object.freeze({
			Id: "ID",
			StartedOn: "Started On",
			SubProject: "Sub Project",
			Company: "Company",
			Teams: "Teams",
			InvoiceFirm: "Invoice Firm",
			InvoiceFees: "Prof Fees",
			ReimbursementVoucher: "RV",
			AmountReceived: "Received",
			AmountPending: "Pending",
			Total: "Total",
			Status: "Status",
		}),
		Tasks: Object.freeze({
			Particulars: "Particulars",
			Remark: "Remark",
			DueDate: "Due Date",
			Actions: "Actions",
		}),
		TasksRemarks: Object.freeze({
			Task: "Task",
			Remark: "Remark",
			Date: "Date",
			WrittenBy: "Written By",
		}),
		Transactions: Object.freeze({
			All: Object.freeze({
				Date: "Date",
				Module: "Module",
				BankName: "Bank Name",
				AmountPaid: "Amount Paid",
				AmountReceived: "Amount Received",
				Particulars: "Particulars",
				PaymentSource: "Payment Source",
				PaymentType: "Payment Type",
				Remarks: "Remarks",
				EntryBy: "Entry By",
			}),
			General: Object.freeze({
				Date: "Date",
				Firm: "Firm",
				Bank: "Bank",
				Amount: "Amount",
				Particulars: "Particulars",
				PaymentSource: "Payment Source",
				PaymentType: "Payment Type",
				Remarks: "Remarks",
				EntryBy: "Entry By",
			}),
			Invoice: Object.freeze({
				Date: "Date",
				Particulars: "Particulars",
				AmountReceived: "Amt Received",
				PaymentSource: "Payment Source",
			}),
			PettyCash: Object.freeze({
				Date: "Date",
				Firm: "Firm",
				PaymentType: "Payment Type",
				Particulars: "Particulars",
				Remarks: "Remarks",
				AmountPaid: "Amount Paid",
				AmountReceived: "Amount Received",
				Balance: "Balance",
				EntryBy: "Entry By",
			}),
			RvList: Object.freeze({
				Date: "Date",
				Id: "ID",
				Amount: "Amount",
				Download: "Download",
			}),
		}),
	}),
	ToastTypes: Object.freeze({
		Error: "error",
		Information: "info",
		Success: "success",
		Warning: "warning",
	}),
	UserMenu: Object.freeze({
		Activity: "Activities",
		Employees: "Employees",
		// Profile: "Profile",
		// Settings: "Settings",
		Logout: "Logout",
	}),
	UserType: Object.freeze({
		Administrators: "Administrators",
		Employees: "Employees",
	}),
});

export default MyConstants;
